### ISSUE TITLE
Retrieve entire chain spec

### ISSUE THREAD

**Issue by kianenigma** [paritytech/json-rpc-interface-spec#157] opened 2024-06-07 02:22 UTC
I see a number of methods that return specific parts of the chain-spec such as properties. 

Would it be possible to also serve the entire chain-spec over RPC? This would be useful in https://forum.polkadot.network/t/polkadot-parachain-omni-node-gathering-ideas-and-feedback/7823. 

Similar to the discussion in https://github.com/paritytech/polkadot-sdk/issues/60, the format of the [chain-spec in polkadot-sdk](https://paritytech.github.io/polkadot-sdk/master/sc_chain_spec/index.html) is pretty questionable to me, but I don't have strong opinions yet about what else it should be. It might be a good idea to revise the format before exposing it over a standardized RPC

**Comment by tomaka** [comment] 2024-06-07 07:42
This is a duplicate of https://github.com/paritytech/json-rpc-interface-spec/issues/68

**Closed** 2024-07-22 08:50 UTC
